# The directory to backup
local_root: /mnt/data
# A sas url with read, write, delete and list permissions for the blob container you want to use.
sas_url: "<sas url>"
# How many versions of a file to keep
num_versions: 4