name: Release
on: 
  push:
    tags:
     - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker compose build
      - name: Push the image
        run: >
          source version &&
          docker compose push &&
          docker tag ghcr.io/floriankramer/azure-blob-backup:${VERSION} ghcr.io/floriankramer/azure-blob-backup:latest &&
          docker push ghcr.io/floriankramer/azure-blob-backup:latest
      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          source version &&
          docker create --name temp-image ghcr.io/floriankramer/azure-blob-backup:${VERSION} &&
          docker cp temp-image:/usr/local/bin/azure_blob_backup ./azure_blob_backup &&
          docker rm -v temp-image &&
          gh release create ${VERSION} "./azure_blob_backup#Alpine"